version: "3"
services:
  octoprint:
    image: ghcr.io/sgsunder/octoprint:latest
    ports:
      - 8080:5000
    environment:
      # Replace with your own values
      OCTO_USER: ssunder
      OCTO_PASS: hunter2
    volumes:
      - ./config:/etc/octoprint:rw
      # generally a good idea to also persist webcache to speed up restarts
      # but no need to back this data up
      - webcache:/etc/octoprint/generated
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    logging:
      driver: local
      options:
        max-size: "1m"
        max-file: "1"
        compress: "false"
    restart: always
volumes:
  uploads:
  webcache:
