appearance:
  color: black
  fuzzyTimes: false
feature:
  keyboardControl: false
  printStartConfirmation: true
plugins:
  consolidate_temp_control:
    layout: vertical
  custombackground:
    background_url: /plugin/custombackground/static/img/ocotoprint-transparent.png
  widescreen:
    right_sidebar_items:
    - files
    use_useragent: true
printerProfiles:
  default: _default
serial:
  baudrate: 115200
  blockedCommands:
  - M0
  - M1
  - M600
  pausingCommands:
  - M0
  - M1
  - M25
  - M600
server:
  firstRun: false
  onlineCheck:
    enabled: false
  pluginBlacklist:
    enabled: true
  seenWizards:
    backup: null
    corewizard: 4
    tracking: null
temperature:
  profiles:
  - bed: 70
    chamber: null
    extruder: 210
    name: PLA
webcam:
  timelapseEnabled: false
  watermark: false
  webcamEnabled: false